### ISSUE TITLE
Font Poppins doesn't support cyrillic

### ISSUE THREAD

**Issue by yoyurec** [sokirill/logseq-panic-theme#1]
Suggest to replace it with alternative font Mulish
https://fonts.google.com/specimen/Mulish

![image](https://user-images.githubusercontent.com/137919/146779372-f4a20ae8-8909-484c-9021-1d77126b7eee.png)

**Comment by sokirill** [comment]
Changed to Mulish. Use the import link for now as I haven't submitted the PR yet (need to improve the menu CSS).
