### ISSUE TITLE
Bullet threading broken

### ISSUE THREAD

**Issue by ingepettersen** [sokirill/logseq-panic-theme#4]
Should be updated, as the Dev theme allready has been. This change in Logseq breaks the current bullet threading: https://github.com/logseq/logseq/pull/3559

Hoping for a quick fix 😊 Love this theme!

**Comment by sokirill** [comment]
👋 Thanks for the note. I just pushed the change to the main code base but still need to submit a PR to the marketplace. In the meantime you can use the import: @import url('https://cdn.jsdelivr.net/gh/sokirill/logseq-panic-theme@latest/custom.css');
